# Generated by Django 4.1.6 on 2023-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sem',
            field=models.CharField(default='s1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(default='2020-2024', max_length=20),
        ),
    ]
